# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: Suprim Regmi
# Description of the Site
description: Software Engineer
# URL of Image of the Site
#site-image: /WhatATheme/assets/images/meta.jpg
site-image: /WhatATheme/assets/images/focusing.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: /images/Author.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: suprimreg@gmail.com
facebook_username: suprimregmi
twitter_username: suprimregmi
instagram_username: suprimregmi
linkedin_username: suprimregmi
github_username:  suprimregmi
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# # Google Analytics
# google-analytics: UA-163806439-1

# # Disqus
# disqus-shortname: thedevslot

# Name of the Author
author-name: suprimregmi
# URL for the Image of the Author
# author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# author-image: /WhatATheme/assets/images/Author.jpg
author-image: 
# 60 Words About the Author
author-about: I'm delving into Data Engineering, actively honing my skills in Power BI and data visualization. My focus is on understanding big data and analysis, guiding me on an enriching learning journey in this field.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAL0AyAMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAAAQMEBQYCBwj/xAA6EAABAwMCBAQCCQMEAwEAAAABAAIDBAUREiETMUFRBiJhcTKBBxQjQlKRobHRweHwJENi8TNTchb/xAAZAQADAQEBAAAAAAAAAAAAAAAAAQIDBAX/xAAgEQACAgMAAwEBAQAAAAAAAAAAAQIRAxIhEzFBIjJh/9oADAMBAAIRAxEAPwD05CELrFYIQhAWCEISATCQ+66VR4hv9PZaUyy+d2dmZwUnwC2x5SR0XAIIzqAHTJwSvKK76ULg2T7KGAAtxvqKzt/8aV11qI36zDpbpMbXkNznPJTaA9vluVDFIYn1cAkb8TTIMhV1T4tsNMXCS5Ramu0lrAXfsvCorjLrcZTnVzOnJKksfFUAhrcnnk/3SsD2yLxbYpW6m3GIb4w/yn9VbMqYHsD45mPaeRY7OV898Bmc6nMd3HLKciuFxo2NFPUSNYzk1jsYRsB9DDBGd8dEBeVeHvpBrII2wXPMrQNj97K3Vl8S2+6gNilDZSM6HAj/AL+WUwLpGF1j/rOUYTA5LQkXeEmlMDhGF1gowU7A5whdYKTSiwEKEuEIsQ6hAQgYqRKuSSgBUJMpMlFhQxcqxlvoZ6uXdkTC7+F4F4lvtVebk6WoeS0uOlgO2F6T9K12dBa2W+GQtkqDl2Pw7j915KGtAGj4g3OSokwIs2W7ZAOOgTUbt843znKnsopJ5XFrCQNlYjwxWNYXNYXYGdgsrL1ZRkahpxunGSSROOXDB3xhT/qElO4sqYy09HdCnBQF4/8AGSO4TTDVjcMwkZgAEjm3GEA8QkDGr1XElKIHgNLg7qE8WODSZC17T1BVE0cNDXu0E6TnOSpENdLQOEkFS5r85GD/AJlNMLAxzZGkgDYdVzpa6MDWBg7ZSsD13wP4ujvDBBVOayqYCMfjHcLYgjGc7L54opZrfVwVdO4skjIeAO/ove7dV/XLfT1AxpmjD9vUK4ysRMyO6MrjWUmoqgHNkmU3qKNRSAcQuNRRqKAOsoXGUIoLHUICFQAhBQSgBCEJUhSGePfSTI6W/Oa4HyMAafQrKvgJELWDzSvAHtnC130sUctLcxVYyypDdx3bz/os1Ygam40o5hjcn0OVnJjirNv4etEekGRo+DB26rQwWSIk4JGegKW3xaGNx7q3hcAuRu2dsVSM/XeGoapuh4J/CqL/APJ1NI/iUpOx3b/2vRnPYcYI2QQD0CNmLRM8+lsEdUwR1lO6KUffDdlU1fguaKN8sAa9rTt02Xqp0acY2UeTQGuYB5XDBRu0EsaZ4pWU77edMjSCM7Y2IVJLI7iOd3Oy9kudjhq4zG8NJzlhwvPfFPh91GwyRMJHIgDl6q1lsxliKKnqTqAc4nBzuvefCRz4ctxHIwNIXz5EMy6e/JfQ3haEweHbdE7n9XYfzAK6IHOy0QjASLShAhCEACEJEhioSISsB4IQhXYwSLoJCgAKMoSYUgYj6Wqdslhp5sHMdQBt0BBz/RYfwbSOdW8QNyBuSOi9I8aTU9ZaK23uD9WjVrDchrhvv2Hqs34HpOHaDLtlzzv7FY5Ha4a44u+mkgJaWt2PffkrKGM9T+iy8kNzrqmRsTxTU+cA/ed6rt9jqI48m9zhx5DP991goo32Zr2wcsb5SFjwdwcLN211TREcWtfKB+ILTU9Rx2ZHZTJI0jI5MeN3OwPfCbcYnjDXg98FRbu8OaGyHGeyzj7RTzSOc2aojJdnUxx/ohJMTbXov6tmjcfIKqucTJ6Z2PNqbnB/ZNusk2GmK6zOc0baxn2/RSKZs+gxVTQ57PvN5PHdJxphF7Lp5HPQiOtkw3Aa9e+2tpbbKJvanYP0C8mvlvLb6Ys4ZM8OyByBXq1urYJWRwRCQFjQBrbjIC6sUl9OKcHZOSIQugzBCEJMYJEISAEIQpAeJSJMoymM6yuS5CTCYjoFC5XRKB2UD2NlqKwvwAXO59VW+FYA2zwggDUC7Hure8RaXOIGNeCcKssjgyijYDs3IB+a5Hw7U7SYt4hqWxgUri3LuY6BZ+6+G5qysgno3NdHhol473EtIznG+43/AEC3TI+KG53T4poo/uBJNobimUc8DNbOC1zA0aXHOzlJoZnRMMeeQT9a0AYPLOE1RtG+3NTIqKI1eTM/LuYHVU3iK1PudJTNo4Y+JE7ziZx8wyD0I7Y9iVoZmh0p2znupcEbcgPaCPZKLoJxsy9Lbn0cFHDG5zpmt+2IJxnPTKv4YfKCRv37qwfTsO7QPdRZPsxhJ9GuFBPSMPiaie4D/wAbgHHoRhXM2mCtgewAtyG7Doqufh1F6pYpD8McjiT/APKsre3juiLs4b5k1baDiTZcoQheieaCEISYAkSpFIAhclCAHkhK5yhVQjtC5QihnWUhK5yhOhEetjEkJd1bkn2WTtcgbUVEAzpZO4AHtlbKVokY5p2Dhg4WMr6d1vvj27YlaJOfy/osMsfpvjnyjSUshGPRWQ06clUlHIHtDhyKsmyDGCVznSmRLg4HqPU9F3bouJGHD0UW6Mjlpntc4BnUpi21LhDphmDg3v09UmWmS6lpErtO4B3x091NpcaWg88BUckZmrI3uqSXg8g44x7K7gAaWnP5qENsdmOI8AqBO/DS49FLnPkVTcJgyncOqYilpXGrv0mX6WMid8xkfytdb4gyHVjfosv4bonz1NXOxvlbiMHseZ/otjG0MY1g5AYW+OHbOfJP80jpCRKumzlBCEFAAkJRlclIAKEiEDHEIQrJBCEIAEIQgAWb8Z0+IaWsY3eOThvI/Cf7/utIoF9FO6z1gqpRHDwjmQ76ex/PBUyXBxfTN2is0kB7iACpV7uEjIo205Ic/Ye6ydqucUmHOOx/fdWslbHPUwDW0NacnK5KOxPh0wmVpjqHTSuHxN0kAKfTS0kbOGafh5bjynmOyekhjeGyxY1d8Lr61G0NEkTdQ7tS4bxSorg2mjm4zJJIdsbkEBPxXSojc3FQyRoIypr/APUnyt0N7YUeuomMptQAGnfZRwJJfC3lnHBDzncZWfuFW0RvdJsAOXdOy1zX0wOsDA5ZWVu18+ovjqGwiVsMrXva7kR0B/VKJnNno/h+kNHbY2OGJZBxH+56KyWc8K+L7f4jZogdwasAOdC7f3IPVaMldsXw4WBSFGUKhAglGUiABIhCBghCEAOISZShXYqBCEiAFQhCBAvO/peucrKKC307iHPBlfjtuB/X8l6Jkc+nv/VeReNallXc6mZzwW6g1mN/KBjb/OqzyS+FwjfSps1PKywUdfG5xjJcyQ/hIcRn2wrFtSBJGBgAjmVZfR9HFJYHUrg10bZnNe1wz5TuP3/RQ75Z5bWTIwOkpSchw5s9D6eqwjRs48NJaLiwU+iVwyB3UqWv0u8pB82AsHR3TDdLwGnGx6H5qzjrY5I24duDnY9FMlRUZujbx1cTIdUjwO2FQ3K5gktcTpIyMdVT1FzGDrk0gcvRVM1yNQcNcSIx5Xfi+Siit2WNwq2aS5uQ7VkBv7JjxZQPpfBb5JsGpllZJN3BJ2Vr4as01TOK+4xhjGn7GI9f+SneOaUVXhyri7APGPQj+FFoqm0eVeEqqSjvFPURPLXRuB2Oy+jKadtTTxTM+GRocPmvmq0U0n1glozgY2Xt30eXQVlndSSP+3p3YAJ+JvTH6rqxM5WuUatKkzv+/ohbEAlSIQAIQhMAQgIQIUJQkyjOP4RYxSSjJ7FM1NVDSwGapkZHGPvOdhZ+t8YQZ0Wxn1kn/cOzfyScq9glbpGlklZE1zpHBjBzc44WfrfGVqp2u4MoneOxwPz6/LKxt9mrrg8SVVW+TzYEOcNHoAOao6ihdIA0yZPQDkPfuoeVP0aeNourt4sqLtVClfI6KAnUWsONuZz327rO1r31tWQ0ZBPlA6BPVlDwJmcPJecMOOpVmKWOmgaQWh2nzPKxc+Gjg/TH/Cr3WqrjMrswVH2bz+F3QrfSwNcxwcGua7odwQvM21zHskgDeI3Ocre+GLi2ppGwyu1PYC0E9Vm7T6aRprhT3PwjTzuL6b7InmAMhUh8IXAuw1sT24xkPLV6XJA4eZh+Sa8w+Ju/qnsGp56zwVWPJMz4oweocX/wru0+GKSifxHtMr29XD9lqHyOkGMORHCXHU7ZZtlKI1FCAzkqLxpUMprDVOc7443MHqStPKWsYSdgAvOfF07rrXR0zfNTxvHl/Ek0V8M7YImQQsDnDiPOrBH6KdUtltbHVdG5wB5lpxhQq+CWmlZkaSOo7qzFVHVUDoZcB5ZpI7rX+aowVO0y28PePqiIMhuDDUM+67OHj27/ADXoFDcaWuZqgkGrGdDtnD5f4PVeM0ducZxw3t3B3IVqK6Wic2OpD9QGWSMO618teiFi509cO2R1HNC82tfje4UrsVOKyE8gTpe32OP3W1tN/oLpGDDLokP+1IMOC1UkzJpotEFAPfA223SEqyQzhKuSUqAG6iphpozJPI2No6uOFnbj4sY3XFb2lxzjiu2AWArqusuNQZq6d8h7ath7Dp8lBFdNGCyMaG53A3/dZybfotUvZfV9LXXKp41bVvmz+I4Dfl/C4hZ9Uy1hI3IIHVR47rVadRka7y5w5oUJorLrVPbHIQM7nlhY1J/0za0v5RYy10cbXPLNT9GMk8lBFyjOg8N2c77807XWqeCnc0YdtjIKhQUFQZGgsDd+pRFQoJSlZJFaZKocRoa1uHZz2TNwqXVWdOSzOQO4SVNtmjillLtWOgVnR00VNScacgHTkuPT0CVxXUOpS4yBbaR7qlhlyxh5g8yrmiqH2u7Mi1u4UuNBPQ9lm7lfpxqit7Cx4OOKRk/JV9mr7h9fJq5XyNO7tQzv6dlLkp9CnDh7tQ1bZowHHDupUnV+NuVhfD/iKKQsZLqY7ODlbCCrieATIPZTRpaJTnjoAuNelup5AC5lkaIy8Dy9CVm73f46NzIWN40z8YbqwAnoxbr4OXq5OkJhhzy3d2WVMrIasySY0sBxg/CO6YuV1rpNUUQbGXfdasXUi409W6Zr3uJOHE8iO2ErQScqs2vBjryeI7Id5gR0Vbdqd9JKzfLAc5CiWa6PD9TAWEfFGdx8ireuqG19OWxbOLMaT03Tj+X/AITyUf8ASNa7nEJGiRjmfqrWeaKcYjIcRt6qioLdUmRuloJ36pK9stLUYdqYcZz3V6RcuE7yS6X1II5DplDdQUiq0MjadPXALTgj5rM0DXPe4nW72yn6oyQRNLXuB7I0/Xsryfn0XlP4ovVtlbw38emZ8TH77fuFr7B4uobv5JAaabHwvPlcfR38rzShrqjOdTcYxhwTk9wLd2xMbk5OkEZWkZSToxqMlZ7RqB6oXmVj8bS0YZDOx80PUE7s9j1QtdmRqiLT2xxa2SSUNLubcZTbrdTRyPyNWepKkRXBjKcxuy6Vpxt+6ray5SmYGNrWtc3O++65Y7NnTLSMSe6kpDTfAA7BGQVxbJ6SjmezUBjOeu6pxdah32Y06tWcYRSteJXF4IJbvtzT050nyLlGlqaqF8bhrYeXMqBx4myt87R81WVTdLXB2xyo9OPt2gZO/ZOGONewlle3ov31lNwZMyZ26NVVW1zJWMYS5zWDYYTk8LzE7htecg8mqE2lqP8A1P8AyQscaCeSTYrYYnyul0PyNxsk48D3NkZEQ4bEq0ZRT/ehJ+Sq5LfUh78REDJ2ylCEKCcp+xwzwtlbIx3M+Ycl6B4bqqW4ULGh547AQcO5hYWa2zyx8UQOzp8w23VdSVVTbpy+B72iN2XAdCOqcYpfRTk/qPVap0RDhLKeHGMuydh3WIqKyCrrZKhpDIgdvN0CiVF6raunmiGr7d+5A2IHMKB9Snl0tYw6Bz6bpzqS1IhceosIK1k0jpDG4tLsBJcauFzQzg4HPZSIbZUNgaBF07hRK+gqTOAIzsO47KIQhZrKU9SFTRRteXwg57YUxjmRSvlkdoywDTjfPVd0FBUaS4QkebBICS40kzQ0OjcN+2U6ipE3LUl2yph4wL3jYEqVXcGZ7HtDHAbZ05wqClikEp8j9h2TlTJLTvaYyWZ7hDxrbjGsj16aC0tGh+A0YxvyS17mgRjDTnnss/RVEz3uy5xzjlsiorakSFpedh1R43sPyrUuKO30z3yF0YB22yurhbad0HkaWnPRyr7dX1DdUgw9pON11X3Z+Gjhjffmp0nsPaDiNQ2lz5BolGAOrP7oTluuI4uXxbAb4Qm5TTElBoboWyzTtYRr4jMt9QpFRaJQQ97gG5+7/nuolskdC6icDlzXiP36LU1UYkglzyAyESm0+BGCapmXttJG6tlmadQj8mD3V9b2fbv55DVmopJYKfMchHEJcfcqTQVk4e48Q8lUoOSJjNRZoqtjDC4uY0nPYKJSMjFQ3DG81VVNxqo2nEpOT1Capa+p4zTxD+SmON6lyyx2NbMAI3bZGDyCrM46ke6r6irmfG8ukdsDtlVfEkPORx+acMToU8qs3GxPTGM81UTEceQ7/EdsqFqfo+N3LuqmV7uK7zHdx6lEMQTy8NhR44A5ZGeyqrzC2OZhjx9qNLthv6qupZHNjB1HdM1srzUxkknTGXAE+qXjpg8q1Lm0sjklcwAaWAFoTrx/qH6QOaqqGZ4hbg4LvicOZUF0r3zOLnE5d39ULH0byUuG5ZgADI29AquocDNISB26Kt1EcifzVXM4mZ3qSiGLop5uGzoW4gI/5beZN17m5aM781nqR5ETMZTdwe8Padbvh7pLFcgeVKJoqBn2rzgEDZJeaaOWDEjevPCoaGpmDZDxZOQ+8nKqvqWxDEp3PXdDxvbg1kWvUTrfQQM1HSXcuZXF3tsJljkiGj2TFDdXGnceE3O3VOVtylkhYHNb8WNkv3ZVw19DlDag6nIMnPf4eijV1tcZGtEw2H4VcxnQ2LT+HCj1B/1D3bdk4yk3YOEaorI6KWlglmkALRslT16kcLS0N21SAoVW2RrFej//2Q==

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
